cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# Special
foreground #dcdfe4
background #0d0f13

# Black
color0  #1e2124
color8  #1e2124

# Red
color1  #f04747
color9  #f04747

# Green
color2  #43b581
color10 #43b581

# Yellow
color3  #faa61a
color11 #faa61a

# Blue
color4  #51A4E7
color12 #51A4E7

# Magenta
color5  #9b59b6
color13 #9b59b6

# Cyan
color6  #00b0f4
color14 #00b0f4

# White
color7  #979c9f
color15 #dcdfe4

# Cursor
cursor             #7289da
cursor_text_color  #ffffff

# Selection highlight
selection_foreground  #ffffff
selection_background  #7289da

# Optional: enable background opacity (for transparency)
background_opacity 0.9
