[Login]

# Batería: cerrar tapa = apagar completamente
HandleLidSwitch=poweroff

# Cargador: logind no hace nada;
# Hyprland/Ambxst se encargarán del lock + OLED
HandleLidSwitchExternalPower=ignore

# Si alguna vez usamos dock/varios monitores
HandleLidSwitchDocked=ignore

# En batería, cerrar tapa se ejecuta aunque una app
# esté inhibiendo sleep/shutdown.
LidSwitchIgnoreInhibited=yes
