general {
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false

    before_sleep_cmd = ambxst lock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    inhibit_sleep = 2
}

# 5 minutos → bloquear
listener {
    timeout = 300
    on-timeout = ambxst lock
}

# 10 minutos → apagar OLED
listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# 30 minutos → suspender
listener {
    timeout = 1800
    on-timeout = ambxst suspend
}
