# =========================
# General
# =========================
general {
  border_size = 2
  col.active_border = rgb(51A4E7)
  col.inactive_border = rgb(143664)
}


# =========================
# Misc
# =========================
misc {
  vfr = true
  vrr = 2   # VRR solo fullscreen (menos parpadeo)
}


# =========================
# Binds settings
# =========================
binds {
  allow_workspace_cycles = true
}


# =========================
# Layouts
# =========================
dwindle {
  pseudotile = yes
  preserve_split = yes
}
