# =========================
# Input
# =========================
input {
  kb_layout = us,latam
  kb_options = grp:win_space_toggle
  follow_mouse = 1

  touchpad {
    natural_scroll = yes
  }

  sensitivity = 0
}

xwayland {
  force_zero_scaling = true
}


# =========================
# Gestures (nuevo sistema)
# =========================
gestures {
  # variables siguen existiendo (gestures:workspace_swipe_*)
  workspace_swipe_min_speed_to_force = 10
  #workspace_swipe_invert = true

  # reemplazo de workspace_swipe/workspace_swipe_fingers:
  gesture = 3, horizontal, workspace
}
