# =========================
# Monitors
# =========================
# EXTENDIDO (recomendado con tus workspaces por monitor)
# MIRROR (si algun dia lo quieres, comenta las 2 lineas de arriba y descomenta estas)
monitor = eDP-1,2560x1600@240,0x0,1
monitor = HDMI-A-1,2560x1440@144,0x-1440,1

#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
#monitor = eDP-1, 1920x1080@60, 0x0, 1, mirror, HDMI-A-1

# Reserved area (sintaxis actual: TOP, BOTTOM, LEFT, RIGHT)
#monitor = eDP-1, addreserved, 0, 0, 0, 0
