# =========================
# Window Rules (sintaxis nueva 0.53+)
# =========================
# Que no roben foco al abrir
windowrule = no_initial_focus on, match:class ^(org\.telegram\.desktop)$
windowrule = no_initial_focus on, match:class ^(elecwhat)$
windowrule = no_initial_focus on, match:class ^(discord|discord-canary|Discord)$
windowrule = no_initial_focus on, match:class ^(rog-control-center|RogControlCenter)$
windowrule = float on, match:class ^(Rofi)$
windowrule = float on, match:class ^(org\.kde\.polkit-kde-authentication-agent-1|hyprpolkitagent)$
windowrule = float on, match:class ^(org\.gnome\.Calculator)$
windowrule = float on, match:class ^(org\.gnome\.Nautilus|nautilus)$
windowrule = float on, match:class ^(eww)$
windowrule = float on, match:class ^(pavucontrol|org\.pulseaudio\.pavucontrol)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(blueberry\.py)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org\.gnome\.Settings)$
windowrule = float on, match:class ^(org\.gnome\.design\.Palette)$
windowrule = float on, match:class ^(xdg-desktop-portal|xdg-desktop-portal-gnome)$
windowrule = float on, match:class ^(transmission-gtk)$
windowrule = float on, match:title ^(Color Picker)$
windowrule = float on, match:title ^(Network)$
windowrule = float on, match:title ^(web\.whatsapp\.com_/)$
windowrule = float on, match:class ^(org.telegram.desktop)$
windowrule = float on, match:class ^(rog-control-center)$
windowrule = float on, match:class ^(discord)$
windowrule = float on, match:class ^(elecwhat)$

# Sizes (float)
windowrule = size 1400 900, match:class ^(org\.gnome\.Nautilus|nautilus)$
windowrule = size 1400 900, match:class ^(rog-control-center)$
windowrule = size 2200 1400, match:class ^(discord)$
windowrule = size 1100 770, match:title ^(web\.whatsapp\.com_/)$
windowrule = size 1800 1200, match:class ^(elecwhat)$
windowrule = size 2200 1400, match:class ^(org.telegram.desktop)$
windowrule = size 600 400, match:class ^(blueman-manager)$

# Assign apps to workspaces
windowrule = workspace 3, match:class ^(code)$
windowrule = workspace 7, match:class ^(org.telegram.desktop)$
windowrule = workspace 4, match:class ^(Vmware|vmware)$
windowrule = workspace 2, match:class ^(chromium)$
windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 2, match:class ^(Brave-browser|brave-browser|brave)$
windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 4, match:class ^(obsidian)$
windowrule = workspace 3, match:class ^(burp-StartBurp|burpsuite|BurpSuite)$
windowrule = workspace 6, match:class ^(discord)$
windowrule = workspace 5, match:class ^(Spotify|spotify)$
