# =========================
# Startup
# =========================
exec-once = kitty

# Arranque silencioso: no cambia de workspace ni hace parpadeo
exec-once = [workspace 7 silent] sh -lc 'sleep 5; Telegram -startintray'
exec-once = [workspace 6 silent] sh -lc 'sleep 5; discord-canary --start-minimized'
exec-once = [workspace 9 silent] sh -lc 'sleep 5; rog-control-center'
exec-once = [workspace 8 silent] sh -lc 'sleep 5; elecwhat'

#exec-once = rog-control-center
exec-once = nwg-look -a
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Lavanda-Sea-Dark'
exec-once = bash -lc 'for agent in /usr/lib/hyprpolkitagent/hyprpolkitagent /usr/lib/polkit-kde-authentication-agent-1 /usr/libexec/polkit-kde-authentication-agent-1 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 /usr/lib/lxqt-policykit-agent /usr/lib/mate-polkit/polkit-mate-authentication-agent-1; do [ -x "$agent" ] && exec "$agent"; done; exit 0'
exec-once = hyprctl setcursor Qogir 24
exec-once = ambxst

# Volume
exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
